var miguel = {
  nome: "Miguel",
  idade: 19,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 49,
}
var davi = {
  nome: "Davi",
  idade: 25,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 59,
}
var arthur = {
  nome: "Arthur",
  idade: 16,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 69,
}
var pedro = {
  nome: "Pedro",
  idade: 23,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 79,
}
var gabriel = {
  nome: "Gabriel",
  idade: 19,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 89,
}
var bernardo = {
  nome: "Bernardo",
  idade: 28,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 99,
}
var lucas = {
  nome: "Lucas",
  idade: 33,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 109,
}
var matheus = {
  nome: "Matheus",
  idade: 28,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 119,
}
var rafael = {
  nome: "Rafael",
  idade: 30,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 129,
}
var heitor = {
  nome: "Heitor",
  idade: 37,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 139,
}
var enzo = {
  nome: "Enzo",
  idade: 29,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 149,
}
var guilherme = {
  nome: "Guilherme",
  idade: 15,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 159,
}
var nicolas = {
  nome: "Nicolas",
  idade: 39,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 169,
}
var lorenzo = {
  nome: "Lorenzo",
  idade: 27,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 179,
}
var gustavo = {
  nome: "Gustavo",
  idade: 24,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 189,
}
var felipe = {
  nome: "Felipe",
  idade: 20,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 199,
}
var samuel = {
  nome: "Samuel",
  idade: 17,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 209,
}
var joaoPedro = {
  nome: "João Pedro",
  idade: 15,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 219,
}
var daniel = {
  nome: "Daniel",
  idade: 28,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 229,
}
var victor = {
  nome: "Victor",
  idade: 19,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 239,
}
var leonardo = {
  nome: "Leonardo",
  idade: 30,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 249,
}
var henrrique = {
  nome: "Henrrique",
  idade: 34,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 259,
}
var theo = {
  nome: "Theo",
  idade: 30,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 269,
}
var murilo = {
  nome: "Murilo",
  idade: 25,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 279,
}
var eduardo = {
  nome: "Eduardo",
  idade: 23,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 289,
}
var pedroHenrrique = {
  nome: "Pedro Henrrique",
  idade: 32,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 299,
}
var pietro = {
  nome: "Pietro",
  idade: 40,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 309,
}
var caua = {
  nome: "Cauã",
  idade: 14,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 319,
}
var isac = {
  nome: "Isac",
  idade: 29,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 329,
}
var caio = {
  nome: "Caio",
  idade: 21,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 339,
}
var vinicius = {
  nome: "Vinícius",
  idade: 25,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 349,
}
var benjamin = {
  nome: "Benjamin",
  idade: 27,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 359,
}
var joao = {
  nome: "João",
  idade: 17,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 369,
}
var lucca = {
  nome: "Lucca",
  idade: 19,
  salario: 0,
  contrato: "sem contrato",
  posicao: "indefinida",
  personalidade: "tranquilo",
  media: 0,
  jogos: 0,
  gols: 0,
  assistencias: 0,
  cartoesAmarelos: 0,
  cartoesVermelhos: 0,
  contusao: 0,
  posicaoMenu: 379,
}

var goleiros = [];
var zagueiros = [];
var meias = [];
var atacantes = [];
var jogadoresPeneira1 = [miguel, davi, arthur, pedro, gabriel, bernardo, lucas, matheus, rafael, heitor, enzo, guilherme, nicolas, lorenzo, gustavo, felipe, samuel, joaoPedro, daniel, victor, leonardo,
  henrrique, theo, murilo, eduardo, pedroHenrrique, pietro, caua, isac, caio, vinicius, benjamin, joao, lucca
];
var jogadoresDaPeneira1 = [miguel.nome, davi.nome, arthur.nome, pedro.nome, gabriel.nome,
  bernardo.nome, lucas.nome, matheus.nome, rafael.nome, heitor.nome, enzo.nome, guilherme.nome,
  nicolas.nome, lorenzo.nome, gustavo.nome, felipe.nome, samuel.nome, joaoPedro.nome, daniel.nome,
  victor.nome, leonardo.nome, henrrique.nome, theo.nome, murilo.nome, eduardo.nome, pedroHenrrique.nome,
  pietro.nome, caua.nome, isac.nome, caio.nome, vinicius.nome, benjamin.nome, joao.nome, lucca.nome
];
var jogadoresDaPeneira2 = ["João Miguel", "Bryan", "Joaquim", "João Vitor", "Thiago", "Antônio", "Davi Lucas",
  "Francisco", "Enzo Gabriel", "Bruno", "Emanuel", "João Gabriel", "Ian", "Davi Luiz",
  "Rodrigo", "Otávio", "Alexsandro Duarte"
];